use_frameworks!

platform :ios, '11.0'

workspace 'EventTracing-iOS.xcworkspace'
project 'EventTracing-iOS.xcodeproj'

target 'EventTracing-iOS_Example' do
  pod 'EventTracing', '~> 2.0.0' #, :path => '../'
  pod 'EventTracing-iOS-Debug', '~> 1.0.2' #, :path => '../../EventTracing-iOS-Debug'
  pod 'EventTracing-iOS-LogViewer', '~> 1.0.0' #, :path => '../../EventTracing-iOS-LogViewer'
  pod 'libextobjc'
  # pod 'LookinServer'

  target 'EventTracing-iOS_Tests' do
    inherit! :search_paths
    pod 'KIF', :configurations => ['Debug']
  end
end
